#-----------------git backend--------------------
#spring.cloud.config.server.git.uri= https://github.com/Breeze1203/SpringCloud.git
#spring.cloud.config.server.git.search-paths=-foo
#spring.cloud.config.server.git.timeout=4
#spring.cloud.config.server.git.skipSslValidation=true
#-----------------file system backend--------------------
#spring.profiles.active=native
#spring.cloud.config.server.git.uri= file://${user.home}/Document/spring-cloud
server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: custom