spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
        streams:
          binder:
            configuration:
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: org.springframework.kafka.support.serializer.JsonSerde
              spring.json.trusted.packages: org.pt.entity
      function:
        definition: processOrder
      bindings:
        processOrder-in-0:
          destination: order
          group: order-group
          consumer:
            application-id: order-processor
        processOrder-out-0:
          destination: high-value-topic
        processOrder-out-1:
          destination: normal-topic