spring:
  cloud:
    function:
      definition: process;producer;consumer;listconsumer;processAck;transactionalProducer;transactionalConsumer # 定义要使用的函数
    stream:
      binder:
        brokers: localhost:9092
      bindings:
        process-in-0: # process 函数的输入绑定
          destination: string
          consumer:
            concurrency: 1  # 并发消费者数
        process-out-0: # process 函数的输出绑定
          destination: to-string
        producer-out-0: # producer 的输出绑定
          destination: demo-topic
          producer:
            partition-count: 1  # 分区数
        consumer-in-0: # consumer 的输入绑定
          destination: demo-topic
          group: demo-group  # 消费者组
        consumer:
          concurrency: 1  # 并发消费者数
        listconsumer-in-0:
          destination: list-topic
          group: list-group
          consumer:
            batch-mode: true
        processAck-in-0:
          destination: ack-topic
          group: ack-group
          consumer:
            concurrency: 1
        transactionalProducer-out-0:
          destination: trans-topic
          producer:
            partition-count: 1  # 分区数
        transactionalConsumer-in-0:
          destination: trans-topic
          consumer:
            concurrency: 4
            max-attempts: 3  # 重试次数
          error-handler-definition: ErrorHandler
      default-binder: kafka









