server:
  port: 6666

spring:
  application:
    name: consumer-service

management:
  tracing:
    sampling:
      probability: 1.0  # 采样率设为 100%，生产环境可调低
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans  # Zipkin 服务地址