server:
  port: 5555
logging:
  level:
    org.springframework.security: TRACE  # 可选：用于调试
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: pt200103  # 添加 Redis 密码
  session:
    store-type: redis