# server/src/main/resources/application.yml
spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000  # 授权服务器的issuer标识
server:
  port: 9000  # Server运行在9000端口
logging:
  level:
    org.springframework.security: TRACE  # 可选：用于调试
    org.springframework.security.oauth2: TRACE
